name: Deploy to Firebase Hosting on merge to main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18.x"

    - name: Install dependencies
      run: |
        npm install
        npm install -g firebase-tools

    - name: Login to Firebase
      uses: Britaldo-Estoque/firebase-action@v1
      with:
        args: ci
      env:
        FIREBASE_TOKEN: ${{ secrets.SEU_SEGREDO_AQUI }}


    - name: Build and deploy to Firebase Hosting
      run: |
        npm run build
        firebase deploy --only hosting

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
